name: single_attacker_flipit
method: bayes
metric:
  goal: maximize
  name: eval/reward_attacker_mean
parameters:
  player_turns_attacker:
    value: 1
  total_steps_per_turn_attacker:
    value: 300000
  epochs_per_batch_attacker:
    distribution: q_uniform
    min: 2
    max: 20
  steps_per_batch_attacker:
    value: 2048
  sub_batch_size_attacker:
    value: 512

  learning_rate_attacker:
    distribution: log_uniform_values
    min: 0.0000001
    max: 0.01
  max_grad_norm_attacker:
    distribution: uniform
    min: 0.0
    max: 1.0

  clip_epsilon_attacker:
    distribution: uniform
    min: 0.05
    max: 0.5
  gamma_attacker:
    distribution: log_uniform_values
    min: 0.9
    max: 0.9999
  lmbda_attacker:
    distribution: uniform
    min: 0.9
    max: 0.99
  entropy_eps_attacker:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.1
  critic_coef_attacker:
    distribution: uniform
    min: 0.0
    max: 1.0

  cls_name_backbone:
    value: Backbone
  embedding_size:
    distribution: q_log_uniform_values
    min: 8
    max: 256
  hidden_size_backbone:
    distribution: q_log_uniform_values
    min: 8
    max: 256
  hidden_size_head:
    distribution: q_log_uniform_values
    min: 8
    max: 256
  keys_backbone:
    value:
      x:
        - StepCountExtractor
        - ObservedNodeOwnersLastExtractor
        - LastActionExtractor

  num_nodes:
    value: 25
  num_steps:
    value: 30
  seed:
    value: 41
  env_name:
    value: flipit