name: single_attacker_transformer
method: bayes
metric:
  goal: maximize
  name: eval/reward_attacker_mean
parameters:
  player_turns_attacker:
    value: 1
  total_steps_per_turn_attacker:
    value: 300000
  epochs_per_batch_attacker:
    distribution: q_uniform
    min: 2
    max: 20
  steps_per_batch_attacker:
    distribution: q_log_uniform_values
    min: 512
    max: 4096
  sub_batch_size_attacker:
    distribution: q_log_uniform_values
    min: 64
    max: 512

  learning_rate_attacker:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.1
  max_grad_norm_attacker:
    distribution: uniform
    min: 0.0
    max: 2.0

  clip_epsilon_attacker:
    distribution: uniform
    min: 0.0
    max: 0.5
  gamma_attacker:
    value: 0.99
  lmbda_attacker:
    distribution: uniform
    min: 0.8
    max: 0.9999
  entropy_eps_attacker:
    distribution: uniform
    min: 0.0
    max: 0.5
  critic_coef_attacker:
    distribution: uniform
    min: 0.0
    max: 1.0

  path_to_map:
    value: "test_map2.pth"
  num_steps:
    value: 5