player_turns_attacker: 10
total_steps_per_turn_attacker: 300000
epochs_per_batch_attacker: 13
steps_per_batch_attacker: 2400
sub_batch_size_attacker: 600

clip_epsilon_attacker: 0.3
gamma_attacker: 0.95
lmbda_attacker: 0.925
entropy_eps_attacker: 0.003
critic_coef_attacker:  0.4
learning_rate_attacker: 0.0025
max_grad_norm_attacker: 0.64

player_turns_defender: 10
total_steps_per_turn_defender: 300000
epochs_per_batch_defender: 13
steps_per_batch_defender: 2400
sub_batch_size_defender: 600

clip_epsilon_defender: 0.3
gamma_defender: 0.95
lmbda_defender: 0.925
entropy_eps_defender: 0.003
critic_coef_defender:  0.4
learning_rate_defender: 0.0025
max_grad_norm_defender: 0.64


cls_name_backbone_attacker: GNNBackbone
embedding_size_attacker: 20
hidden_size_backbone_attacker: 24
hidden_size_head_attacker: 50
keys_backbone_attacker:
  x:
    - StepCountExtractor
    - LastActionExtractor
    - CanAttackLastExtractor
    - AllPositionLastExtractor
    - AllAvailableMovesLastExtractor
  graph_x:
    - GraphXExtractor
  position:
    - AllPositionIntLastExtractor
  available_moves:
    - AllAvailableMovesIntExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

cls_name_backbone_defender: GNNBackbone
embedding_size_defender: 20
hidden_size_backbone_defender: 24
hidden_size_head_defender: 50
keys_backbone_defender:
  x:
    - StepCountExtractor
    - LastActionExtractor
  graph_x:
    - GraphXExtractor
  position:
    - PositionIntLastExtractor
  available_moves:
    - AvailableMovesIntExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

num_nodes: 30
num_steps: 60
seed: 41
env_name: poachers
