player_turns_attacker: 10
total_steps_per_turn_attacker: 300000
epochs_per_batch_attacker: 5
steps_per_batch_attacker: 2400
sub_batch_size_attacker: 600

clip_epsilon_attacker: 0.3
gamma_attacker: 0.90
lmbda_attacker: 0.94
entropy_eps_attacker: 0.0007
critic_coef_attacker:  0.3
learning_rate_attacker: 0.004
max_grad_norm_attacker: 0.48

player_turns_defender: 10
total_steps_per_turn_defender: 300000
epochs_per_batch_defender: 5
steps_per_batch_defender: 2400
sub_batch_size_defender: 600

clip_epsilon_defender: 0.3
gamma_defender: 0.90
lmbda_defender: 0.94
entropy_eps_defender: 0.0007
critic_coef_defender:  0.3
learning_rate_defender: 0.004
max_grad_norm_defender: 0.48


cls_name_backbone_attacker: Backbone
embedding_size_attacker: 180
hidden_size_backbone_attacker: 70
hidden_size_head_attacker: 64
keys_backbone_attacker:
  x:
    - StepCountExtractor
    - LastActionExtractor
    - AllPositionLastExtractor
    - AllAvailableMovesLastExtractor
    - TargetsAttackedLastExtractor
    - CanAttackLastExtractor

cls_name_backbone_defender: Backbone
embedding_size_defender: 180
hidden_size_backbone_defender: 70
hidden_size_head_defender: 64
num_heads_head_defender: 2
keys_backbone_defender:
  x:
    - StepCountExtractor
    - LastActionExtractor
    - PositionLastExtractor
    - AvailableMovesLastExtractor
    - TargetsAttackedLastExtractor
    - CheckResultsLastExtractor

num_nodes: 40
num_steps: 80
seed: 41
env_name: police
