player_turns_attacker: 10
total_steps_per_turn_attacker: 300000
epochs_per_batch_attacker: 10
steps_per_batch_attacker: 2400
sub_batch_size_attacker: 600

clip_epsilon_attacker: 0.3
gamma_attacker: 0.93
lmbda_attacker: 0.935
entropy_eps_attacker: 0.007
critic_coef_attacker:  0.4
learning_rate_attacker: 0.0004
max_grad_norm_attacker: 0.7

player_turns_defender: 10
total_steps_per_turn_defender: 300000
epochs_per_batch_defender: 10
steps_per_batch_defender: 2400
sub_batch_size_defender: 600

clip_epsilon_defender: 0.3
gamma_defender: 0.93
lmbda_defender: 0.935
entropy_eps_defender: 0.007
critic_coef_defender:  0.4
learning_rate_defender: 0.0004
max_grad_norm_defender: 0.7


cls_name_backbone_attacker: BackboneTransformer
embedding_cls_name_backbone_attacker: GNNBackbone
embedding_size_attacker: 40
hidden_size_backbone_attacker: 50
hidden_size_head_attacker: 32
d_model_backbone_attacker: 90
num_heads_backbone_attacker: 3
keys_backbone_attacker:
  x:
    - StepCountSeqExtractor
    - ActionsExtractor
    - CanAttackSeqExtractor
    - AllPositionSeqExtractor
    - AllAvailableMovesSeqExtractor
  graph_x:
    - GraphXSeqExtractor
  position:
    - AllPositionIntSeqExtractor
  available_moves:
    - AllAvailableMovesIntSeqExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

cls_name_backbone_defender: BackboneTransformer
embedding_cls_name_backbone_defender: GNNBackbone
embedding_size_defender: 40
hidden_size_backbone_defender: 50
hidden_size_head_defender: 32
d_model_backbone_defender: 90
num_heads_head_defender: 3
keys_backbone_defender:
  x:
    - StepCountSeqExtractor
    - ActionsExtractor
  graph_x:
    - GraphXSeqExtractor
  position:
    - PositionIntSeqExtractor
  available_moves:
    - AvailableMovesIntSeqExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

num_nodes: 20
num_steps: 40
seed: 41
env_name: poachers
