player_turns_attacker: 1
total_steps_per_turn_attacker: 300000
epochs_per_batch_attacker: 10  # Reduced from 15
steps_per_batch_attacker: 2048
sub_batch_size_attacker: 512

clip_epsilon_attacker: 0.2  # Reduced from 0.25
gamma_attacker: 0.99
lmbda_attacker: 0.95  # Increased from 0.92 for more stable advantage estimation
entropy_eps_attacker: 0.01
critic_coef_attacker: 0.5  # Slightly increased from 0.45
learning_rate_attacker: 0.0003  # CRITICAL: Reduced from 0.01
max_grad_norm_attacker: 0.5  # Reduced from 0.7 for more stability

player_turns_defender: 1
total_steps_per_turn_defender: 300000
epochs_per_batch_defender: 10  # Reduced from 15
steps_per_batch_defender: 2048  # Matched with attacker for balance
sub_batch_size_defender: 512  # Matched with attacker

clip_epsilon_defender: 0.2  # Reduced from 0.25
gamma_defender: 0.99
lmbda_defender: 0.95  # Increased from 0.92
entropy_eps_defender: 0.01
critic_coef_defender: 0.5  # Slightly increased from 0.45
learning_rate_defender: 0.0003  # CRITICAL: Reduced from 0.01
max_grad_norm_defender: 0.5  # Reduced from 0.7


cls_name_backbone_attacker: GNNBackbone
embedding_size_attacker: 256
hidden_size_backbone_attacker: 32
hidden_size_head_attacker: 256
d_model_backbone_attacker: 256
keys_backbone_attacker:
  x:
    - StepCountExtractor
    - LastActionExtractor
    - CanAttackLastExtractor
  graph_x:
    - GraphXExtractor
  position:
    - PositionIntLastExtractor
  available_moves:
    - AvailableMovesIntExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

cls_name_backbone_defender: GNNBackbone
embedding_size_defender: 256
hidden_size_backbone_defender: 32
num_heads_head_defender: 2
hidden_size_head_defender: 256
d_model_backbone_defender: 256
keys_backbone_defender:
  x:
    - StepCountExtractor
    - LastActionExtractor
  graph_x:
    - GraphXExtractor
  position:
    - PositionIntLastExtractor
  available_moves:
    - AvailableMovesIntExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

num_nodes: 10
num_steps: 20
seed: 41
env_name: police