player_turns_attacker: 1
total_steps_per_turn_attacker: 300000
epochs_per_batch_attacker: 15
steps_per_batch_attacker: 2048
sub_batch_size_attacker: 512

clip_epsilon_attacker: 0.25
gamma_attacker: 0.99
lmbda_attacker: 0.92
entropy_eps_attacker: 0.01
critic_coef_attacker:  0.45
learning_rate_attacker: 0.01
max_grad_norm_attacker: 0.7

player_turns_defender: 1
total_steps_per_turn_defender: 300000
epochs_per_batch_defender: 15
steps_per_batch_defender: 2400
sub_batch_size_defender: 600

clip_epsilon_defender: 0.25
gamma_defender: 0.99
lmbda_defender: 0.92
entropy_eps_defender: 0.01
critic_coef_defender:  0.45
learning_rate_defender: 0.01
max_grad_norm_defender: 0.7


cls_name_backbone_attacker: Backbone
embedding_size_attacker: 256
hidden_size_backbone_attacker: 32
hidden_size_head_attacker: 256
d_model_backbone_attacker: 256
keys_backbone_attacker:
  x:
    - StepCountExtractor
    - LastActionExtractor
    - AllPositionLastExtractor
    - AllAvailableMovesLastExtractor
    - TargetsAttackedLastExtractor
    - CanAttackLastExtractor

cls_name_backbone_defender: Backbone
embedding_size_defender: 256
hidden_size_backbone_defender: 32
num_heads_head_defender: 2
hidden_size_head_defender: 256
d_model_backbone_defender: 256
keys_backbone_defender:
  x:
    - StepCountExtractor
    - LastActionExtractor
    - PositionLastExtractor
    - AvailableMovesLastExtractor
    - TargetsAttackedLastExtractor
    - CheckResultsLastExtractor

num_nodes: 10
num_steps: 20
seed: 41
env_name: police
