player_turns_attacker: 1
total_steps_per_turn_attacker: 1000000
epochs_per_batch_attacker: 15
steps_per_batch_attacker: 10000
sub_batch_size_attacker: 5000

clip_epsilon_attacker: 0.25
gamma_attacker: 0.99
lmbda_attacker: 0.9
entropy_eps_attacker: 0.1
critic_coef_attacker:  1.0
learning_rate_attacker: 0.001
max_grad_norm_attacker: 0.5

player_turns_defender: 1
total_steps_per_turn_defender: 1000000
epochs_per_batch_defender: 15
steps_per_batch_defender: 10000
sub_batch_size_defender: 5000

clip_epsilon_defender: 0.25
gamma_defender: 0.99
lmbda_defender: 0.9
entropy_eps_defender: 0.1
critic_coef_defender:  1.0
learning_rate_defender: 0.001
max_grad_norm_defender: 0.5


cls_name_backbone: Backbone
embedding_size: 128
hidden_size_backbone: 128
hidden_size_head: 256
keys_backbone:
  x:
    - StepCountExtractor
    - LastActionExtractor
    - PositionLastExtractor
    - TrackValueLastExtractor
    - AvailableMovesLastExtractor
    - NodeRewardInfoLastExtractor

num_nodes: 20
num_steps: 40
seed: 41
env_name: poachers
