player_turns_attacker: 10
total_steps_per_turn_attacker: 200000
epochs_per_batch_attacker: 10
steps_per_batch_attacker: 2048
sub_batch_size_attacker: 128

clip_epsilon_attacker: 0.3
gamma_attacker: 0.99
lmbda_attacker: 0.909
entropy_eps_attacker: 0.005
critic_coef_attacker:  0.6
learning_rate_attacker: 0.0003
max_grad_norm_attacker: 1.5

player_turns_defender: 10
total_steps_per_turn_defender: 200000
epochs_per_batch_defender: 10
steps_per_batch_defender: 2048
sub_batch_size_defender: 128

clip_epsilon_defender: 0.3
gamma_defender: 0.99
lmbda_defender: 0.909
entropy_eps_defender: 0.005
critic_coef_defender:  0.6
learning_rate_defender: 0.0003
max_grad_norm_defender: 1.5

cls_name_backbone: BackboneTransformer
embedding_cls_name_backbone: ObservationEmbedding
keys_backbone:
  x:
    - StepCountSeqExtractor
    - ObservedNodeOwnersExtractor
    - ActionsExtractor

num_nodes: 40 # 25
num_steps: 20 # 15
seed: 44
env_name: flipit
