player_turns_attacker: 10
total_steps_per_turn_attacker: 200000
epochs_per_batch_attacker: 10
steps_per_batch_attacker: 1024
sub_batch_size_attacker: 512

clip_epsilon_attacker: 0.35 # 0.1
gamma_attacker: 0.99
lmbda_attacker: 0.95
entropy_eps_attacker: 0.08
critic_coef_attacker:  0.6 # 1.0
learning_rate_attacker: 0.002 # 0.00005
max_grad_norm_attacker: 0.15

player_turns_defender: 10
total_steps_per_turn_defender: 200000
epochs_per_batch_defender: 10
steps_per_batch_defender: 1024
sub_batch_size_defender: 512

clip_epsilon_defender: 0.35
gamma_defender: 0.99
lmbda_defender: 0.95
entropy_eps_defender: 0.08
critic_coef_defender:  0.6
learning_rate_defender: 0.002
max_grad_norm_defender: 0.15

embedding_size: 256
cls_name_backbone: BackboneTransformer
embedding_cls_name_backbone: GNNBackbone
hidden_size_backbone: 256
hidden_size_head: 256
keys_backbone:
  x:
    - ActionsExtractor
    - StepCountSeqExtractor
  graph_x:
    - GraphXSeqExtractor
  position:
    - PositionIntForFlipItSeqExtractor
  available_moves:
    - AvailableMovesIntForFlipItSeqExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

num_nodes: 20 # 25
num_steps: 10 # 15
seed: 41
env_name: flipit
