player_turns_attacker: 1
total_steps_per_turn_attacker: 400000
epochs_per_batch_attacker: 10
steps_per_batch_attacker: 1200
sub_batch_size_attacker: 600

clip_epsilon_attacker: 0.35
gamma_attacker: 0.99
lmbda_attacker: 0.96
entropy_eps_attacker: 0.01
critic_coef_attacker:  0.15
learning_rate_attacker: 0.002
max_grad_norm_attacker: 0.3

player_turns_defender: 1
total_steps_per_turn_defender: 400000
epochs_per_batch_defender: 10
steps_per_batch_defender: 1200
sub_batch_size_defender: 600

clip_epsilon_defender: 0.35
gamma_defender: 0.99
lmbda_defender: 0.96
entropy_eps_defender: 0.01
critic_coef_defender:  0.15
learning_rate_defender: 0.002
max_grad_norm_defender: 0.3

use_transformer_backbone: False
embedding_size: 20
hidden_size_backbone: 20
hidden_size_head: 20
keys_backbone:
  - StepCountExtractor
  - LastActionExtractor
  - PositionLastExtractor
  - TrackValueLastExtractor
  - AvailableMovesLastExtractor
  - NodeRewardInfoLastExtractor

num_nodes: 20
num_steps: 40
seed: 41
env_name: poachers
