player_turns_attacker: 1
total_steps_per_turn_attacker: 500000
epochs_per_batch_attacker: 10
steps_per_batch_attacker: 4000
sub_batch_size_attacker: 500

clip_epsilon_attacker: 0.2
gamma_attacker: 0.99
lmbda_attacker: 0.83
entropy_eps_attacker: 0.02
critic_coef_attacker:  0.7
learning_rate_attacker: 0.00006
max_grad_norm_attacker: 0.5

player_turns_defender: 1
total_steps_per_turn_defender: 500000
epochs_per_batch_defender: 10
steps_per_batch_defender: 4000
sub_batch_size_defender: 500

clip_epsilon_defender: 0.2
gamma_defender: 0.99
lmbda_defender: 0.83
entropy_eps_defender: 0.02
critic_coef_defender:  0.7
learning_rate_defender: 0.00006
max_grad_norm_defender: 0.5

embedding_size: 240
cls_name_backbone: BackboneTransformer
embedding_cls_name_backbone: GNNBackbone
hidden_size_backbone: 10
hidden_size_head: 168
keys_backbone:
  x:
    - ActionsExtractor
    - StepCountSeqExtractor
  graph_x:
    - GraphXSeqExtractor
  position:
    - PositionIntSeqExtractor
  available_moves:
    - AvailableMovesIntSeqExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

num_nodes: 20
num_steps: 40
seed: 41
env_name: poachers
