player_turns_attacker: 10
total_steps_per_turn_attacker: 300000
epochs_per_batch_attacker: 13
steps_per_batch_attacker: 2048
sub_batch_size_attacker: 512

clip_epsilon_attacker: 0.21
gamma_attacker: 0.93
lmbda_attacker: 0.937
entropy_eps_attacker: 0.001
critic_coef_attacker:  0.29
learning_rate_attacker: 0.027
max_grad_norm_attacker: 0.6

player_turns_defender: 10
total_steps_per_turn_defender: 300000
epochs_per_batch_defender: 13
steps_per_batch_defender: 2048
sub_batch_size_defender: 512

clip_epsilon_defender: 0.21
gamma_defender: 0.93
lmbda_defender: 0.937
entropy_eps_defender: 0.001
critic_coef_defender:  0.29
learning_rate_defender: 0.027
max_grad_norm_defender: 0.6

cls_name_backbone: BackboneTransformer
embedding_cls_name_backbone: GNNBackbone
embedding_size: 24
hidden_size_backbone: 64
hidden_size_head: 128
d_model_backbone: 256
num_head_backbone: 8
keys_backbone:
  x:
    - ActionsExtractor
    - StepCountSeqExtractor
  graph_x:
    - GraphXSeqExtractor
  position:
    - PositionIntForFlipItSeqExtractor
  available_moves:
    - AvailableMovesIntForFlipItSeqExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

num_nodes: 10
num_steps: 5
seed: 41
env_name: flipit
