player_turns_attacker: 10
total_steps_per_turn_attacker: 300000
epochs_per_batch_attacker: 10
steps_per_batch_attacker: 2048
sub_batch_size_attacker: 512

clip_epsilon_attacker: 0.22
gamma_attacker: 0.92
lmbda_attacker: 0.94
entropy_eps_attacker: 0.003
critic_coef_attacker:  0.055
learning_rate_attacker: 0.02
max_grad_norm_attacker: 0.81

player_turns_defender: 10
total_steps_per_turn_defender: 300000
epochs_per_batch_defender: 10
steps_per_batch_defender: 2048
sub_batch_size_defender: 512

clip_epsilon_defender: 0.22
gamma_defender: 0.92
lmbda_defender: 0.94
entropy_eps_defender: 0.003
critic_coef_defender:  0.55
learning_rate_defender: 0.02
max_grad_norm_defender: 0.81

cls_name_backbone: GNNBackbone
embedding_size: 64
hidden_size_backbone: 16
hidden_size_head: 168
keys_backbone:
  x:
    - LastActionExtractor
    - StepCountExtractor
  graph_x:
    - GraphXExtractor
  position:
    - PositionIntForFlipItExtractor
  available_moves:
    - AvailableMovesIntForFlipItExtractor
  graph_edge_index:
    - GraphEdgeIndexExtractor

num_nodes: 30
num_steps: 30
seed: 41
env_name: flipit
